### ISSUE TITLE
procrustes_alignment , Defualt value of the Iterations number

### ISSUE THREAD

**Issue by Yvonneser** [MICA-MNI/BrainSpace#110]
I'm currently utilizing PCA and Procrustes alignment in running the GradientMap. While examining the [procrustes_alignment ](https://brainspace.readthedocs.io/en/latest/_modules/brainspace/gradient/alignment.html?highlight=procrustes_alignment)function in your code, I noticed that the alignment undergoes iteration, with the default number of iterations set to 10. Is there a specific reason for choosing 10 iterations? Can this value be modified, and if so, in what scenarios should it be adjusted?

![image](https://github.com/MICA-MNI/BrainSpace/assets/75316223/156f917d-c790-4aa7-af41-a42cad2ef4ed)

**Comment by zihuaihuai** [comment]
First, it's possible to change the number of iterations. To do this, call the function and set the n_iter argument to the desired number (e.g., n_iter=THE_NUMBER_YOU_WANT).

As for why we set the default to 10, it's because it provides a good balance between computational efficiency and algorithm performance for most common use cases
