### ISSUE TITLE
Parcellation text labels

### ISSUE THREAD

**Issue by jingjingz** [MICA-MNI/BrainSpace#22]
Hi, I was trying to extract parcel labels with the Matlab package
labeling = labeling.vosdewael_100;
and the results are numeric parcel labels. I was wondering if there is a way to get the text labels for each ROI and the correspondence between the text and numeric labels.
Thanks!

**Comment by ReinderVosDeWael** [comment]
Hi, no text labels exist for this parcellation. However, since this parcellation is simply a sub-parcellation of Desikan-Killiany, you could look for overlap between these parcellations and the DK-parcels and assign labels based on maximum overlap.

**Comment by jingjingz** [comment]
sorry for the amateur question: where can I find a list of Desikan-Killiany parcellation labels?
Thanks!

**Comment by jingjingz** [comment]
my goal is to visualize the DK parcellation on Conte69 template and compare it with my own gradient map. So I would need to know the name of the parcels in each colored ROI of DK parcellation on the Conte69 surface.

**Comment by PeerHerholz** [comment]
Ahoi hoi @jingjingz,

you can check DK related information [here](https://surfer.nmr.mgh.harvard.edu/fswiki/CorticalParcellation) and [here](https://surfer.nmr.mgh.harvard.edu/fswiki/FsTutorial/AnatomicalROI/FreeSurferColorLUT). Regarding overlap, I would follow @ReinderVosDeWael's suggestion and use a small function to assess label assignments based on maximum overlap instead of a manual way using visualizations as they can be quite misleading.

**Comment by jingjingz** [comment]
@PeerHerholz @ReinderVosDeWael 
Thanks a lot for your help.
