### ISSUE TITLE
Matlab - Diffusion mapping - eigs instead of eig

### ISSUE THREAD

**Issue by manea006** [MICA-MNI/BrainSpace#30]
I have been working with the matlab version of BrainSpace for a few weeks now and I have encountered some memory problems. For reference, I am running voxel-wise rather than surface/parcellation-based analyses. I tried using eigs instead of eig for Diffusion Mapping and it seems the outcome is the same (and solved my memory issues). I saw that it's being used for Laplacian Eigenmaps so I was wondering whether there was any reason for not using it for Diffusion Mapping as well. 

Thanks for your help!

**Comment by ReinderVosDeWael** [comment]
The reason they're different is mostly historic: the LE code was taken from a different package whereas we developed the DM code ourselves. Back when I wrote the first version of the MATLAB DM code (2017) the eigs function would give different results on repeated runs due to random initialization. That's why I chose to use the eig function. Since R2017b the eigs function has changed such that it gives identical results on repeated runs - I assume a fixed vector is used for the random initialization. However, that still means that the results of eigs are dependent on the (arbitrary) choice of intialization. Moreover the eigs function is built primarily with sparse matrices in mind. However, there's no guarantee that the input matrix will be sparse. In such scenarios I'm not sure that eigs will always lead to better memory performance. 

I'll think on whether we want to add an option to use `eigs` instead of `eig`, or whether we'll leave this for more adventurous users to tinker with. On the one hand there's clearly cases where this may be preferred, on the other hand such cases may not be clear-cut and I hesitate to provide users with too many options.
