### ISSUE TITLE
diffusion map embedding generates different results each run (python version) 

### ISSUE THREAD

**Issue by sofievalk** [MICA-MNI/BrainSpace#38]
Hi! 

When running diffusion map embedding in the python version using a parcellation of 91 parcels, results are not reproducible, e.g. the numbers change every iteration. This is not the case when using PCA or le, or when using a parcellation with 400 parcels. Would you have any explanation for this behaviour? 

cheers,
Sofie

**Comment by ReinderVosDeWael** [comment]
Hi Sofie,

This is expected behaviour; diffusion mapping is initialized with a `random_state` parameter. If none is provided then the RandomState singleton used by np.random is used (c.f. https://scikit-learn.org/stable/modules/generated/sklearn.utils.check_random_state.html). If you set the random_state parameter at the initialization of the GradientMaps object then the results should be reproducible across runs.
