### ISSUE TITLE
Cannot plot in remote server 

### ISSUE THREAD

**Issue by qniksefat** [MICA-MNI/BrainSpace#63]
I'm trying to `plot_hemishperes` without showing the plots and just save the outputs in a remote server (connected via VScode). I get this error:

```
2021-12-21 13:35:42.964 (   2.130s) [        EEB5B740]vtkXOpenGLRenderWindow.:464    ERR| vtkXOpenGLRenderWindow (0x3d25310): bad X server connection. DISPLAY=
Aborted (core dumped)
```

I've tried the following. All of them work well in my local and all make the same error on the remote; I couldn't resolve the issue with VTK or make the rendering independent of it. 

- I get a `brainspace.plotting.base.Plotter` with `return_plotter=True` and then `._to_image(filename, scale=1, transparent_bg=True)`.
- I get `fig = plot_hemispheres(..., filename=filename, screenshot=True,` 
- I tried `fig = plot_hemispheres(..., embed_nb=True` to get an ipython image, and then save it by `open(fname, 'wb').write(fig.data)`
- I have also tried `surfplot` to employ `savefig`, and it's also dependent on VTK I guess.

The virtual environment is the same on both systems.

**Comment by OualidBenkarim** [comment]
Hi @qniksefat 

That's because there is no X server. You need an X server even if offscreen rendering is used (e.g., `_to_image`, `screenshot=True`, `embed_nb=True`, etc). 

According to what I found (see [here](https://discourse.vtk.org/t/how-to-build-vtk-on-a-supercomputer-without-x-server-and-no-root-previliges/377) and [here](https://marc.info/?l=vtkusers&m=152484201301060&w=2)), there may be 2 solutions:
1. Install a VTK package built with osmesa (you have them in [conda-forge](https://anaconda.org/conda-forge/vtk/files)) - you wont need an X server then:
```
conda config --add channels conda-forge
conda install mesalib vtk
```

2. or install xvcb to emulate the X server - this is actually what we are using to [test brainspace's plotting functionality 
](https://github.com/MICA-MNI/BrainSpace/blob/master/.github/workflows/github_actions_ci.yml)


Many people had similar problems, so please let us know if this works for you

**Comment by pcamach2** [comment]
@OualidBenkarim @qniksefat one thing to try would be adding `matplotlib.use('PDF')` after you import matplotlib, but before importing pyplot. Then you can add `plt.switch_backend('Agg')` before plotting to switch to a headless/display-free rendering and/or include `backend='Agg'` as an argument for `plt.savefig()`

As an example snippet:

```
import matplotlib
matplotlib.use('PDF')
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

data = pd.read_csv('some.csv')
df = pd.DataFrame(data)
filename = "foo_bar.png"
plt.switch_backend('Agg')
plt.figure()
plt.ion()
ax = sns.scatterplot(x='foo',y='bar', data=df)
fig = ax.get_figure() 
plt.ioff()
fig.savefig(filename,backend='Agg')
```

**Comment by ReinderVosDeWael** [comment]
Closing this as there's now an issue (#66) with a recommended workaround (equivalent to 1. suggested by Oualid).
