### ISSUE TITLE
galign.aligned_ field empty after galign.fit(conn_matrix, reference=gref.gradients_)

### ISSUE THREAD

**Issue by Bronte-Mckeown** [MICA-MNI/BrainSpace#7]
We followed [this](https://brainspace.readthedocs.io/en/latest/python_doc/auto_examples/plot_tutorial2.html#sphx-glr-python-doc-auto-examples-plot-tutorial2-py) tutorial. 

After this section:

`galign = GradientMaps(kernel='normalized_angle', approach='le', alignment='procrustes')
galign.fit(conn_matrix, reference=gref.gradients_)`

according to the tutorial, galign.aligned_ should give us the aligned gradients but instead it is empty.

**Comment by OualidBenkarim** [comment]
That's because the code does not consider the scenario of aligning a single dataset, it only computes the gradients. Will amend this in the next version. 

For now, a simple fix is putting your matrix in a list:

`galign.fit([conn_matrix], reference=gref.gradients_)`

then you will find the aligned data in `galign.aligned_[0]`
